ingress:
  ingressClassName: ingress-nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: web.cozy-todo.click
      service:
        name: frontend
        port: 81

    - host: api.cozy-todo.click
      service:
        name: backend
        port: 3001
  tls:
    secretName: tls-certificate
    wildcardDomain: "*.cozy-todo.click"

certManager:
  issuerName: letsencrypt-prod
  email: thangphan.onthego@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretName: letsencrypt-prod-issuer
  dnsSolver:
    dnsZones:
      - cozy-todo.click
    provider: route53
    region: ap-southeast-1
    hostedZoneID: Z05835622XT8SM6G0VX1B

services:
  frontend:
    name: frontend
    type: ClusterIP
    port: 81
    targetPort: 80

  backend:
    name: backend
    type: ClusterIP
    port: 3001
    targetPort: 3000

deployments:
  frontend:
    image:
      repository: 864899847999.dkr.ecr.ap-southeast-1.amazonaws.com/nonprod-cozy-todo-frontend
      pullPolicy: IfNotPresent
      tag: latest
    port: 80
    replicaCount: 1
    resources:
      requests:
        cpu: "250m"
        memory: "156Mi"
      limits:
        memory: "200Mi"

  backend:
    image:
      repository: 864899847999.dkr.ecr.ap-southeast-1.amazonaws.com/nonprod-cozy-todo-backend
      pullPolicy: IfNotPresent
      tag: latest
    port: 3000
    replicaCount: 1
    resources:
      requests:
        cpu: 1
        memory: "256Mi"
      limits:
        memory: "312Mi"
