apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  namespace: monitoring 
type: Opaque
stringData:
  url: 'https://hooks.slack.com/services/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'

---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: nodejs-alertmanager-config
  namespace: monitoring 
  labels:
    alertmanager: prometheus-kube-prometheus-alertmanager
    app.kubernetes.io/instance: prometheus-kube-prometheus-alertmanager

spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    routes:
    - receiver: slack
      match:
        severity: warning
  receivers:
  - name: slack
    slackConfigs:
    - channel: 'alerts'
      sendResolved: true
      apiUrl:
        name: slack-webhook
        key: url
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
