apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  labels:
    release: prometheus
type: Opaque
stringData:
  # TODO: need to hide this one because it is included token for authenticating webhook
  url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA4R1oxNkxSMFUvQjA4SlY4R1JZODUvVnFMREJTSGNxOU1kNnBDNWZsYUdVQmpkCg==

---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: nodejs-alertmanager-config
  labels:
    release: prometheus

spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    receiver: slack
    routes:
    - matchers:
      - name: severity
        value: warning
      receiver: slack
  receivers:
  - name: slack
    slackConfigs:
    - channel: 'alerts'
      sendResolved: true
      apiURL:
        name: slack-webhook
        key: url
      title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
      text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
