apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-nodejs-rule
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/instance: prometheus
    release: prometheus
spec:
  groups:
  - name: nodejs-api
    rules:
    - alert: HighCPUUsage
      annotations:
        summary: "High CPU usage on {{ printf "{{ $labels.instance }}" }}"
        description: "{{ printf "{{ $labels.instance }}" }} has a CPU usage of {{ print "{{ $value }}" }} for more than 2 minutes"
      expr: |
        irate(process_cpu_seconds_total{app="nodejs-api"}[1m]) * 100 > 60
      for: 2m
      labels:
        severity: warning
