{{- range $service, $config := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $service }}
  labels:
    app: {{ $.Chart.Name }}-{{ $service }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}-{{ $service }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}-{{ $service }}
    spec:
      containers:
        - name: {{ $service }}
          image: {{ $config.image.repository }}:{{ $config.image.tag }}
          imagePullPolicy: {{ $config.image.pullPolicy }}
          ports:
            - containerPort: {{ $config.port }}
          resources:
            {{- toYaml $config.resources | nindent 12 }}
{{- end }}
