{{- range $service, $config := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $service }}
spec:
  type: {{ $config.type }}
  ports:
    - protocol: TCP
      port: {{ $config.port }}
      targetPort: {{ $config.targetPort }}
  selector:
    app: {{ $.Release.Name }}-{{ $service }}
{{- end }}
